name: "GitHub Actions"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Node"
        uses: actions/setup-node@v3
      - name: Install mocha
        run: npm install -g mocha
      - name: Install dependencies
        run: npm install
      - name: "Run Test"
        run: mocha tests/*.js
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
